Milestone 2: App Structure
mohammadumar28/bookstore pull request #2
Opened 2021-01-21 17:36 UTC by mohammadumar28

* Create the basic components
* Create the reducer and actions functions
* Initialize state in the index.js
* Connect all the components to the state

2021-01-21 19:19 UTC, christianotieno requested changes
## Changes Required ♻️ 
Hello @mohammadumar28 👋 
I trust you are doing well. 
Good job with this milestone, we have some few changes to work on before we proceed.
I have left some comments down below 👇 

### Happy coding 💻 
#### Christian Otieno (CR)

2021-01-21 19:19 UTC, christianotieno commented on src/actions/index.js
> +function createBook(book) {
## Implement ES6 syntax
- [ ] Implement this `createBook` action with ES6 arrow function.
```suggestion
const createBook = (book) => {
```

2021-01-21 19:19 UTC, christianotieno commented on src/actions/index.js
> +function removeBook(book) {
## Implement ES6 syntax
- [ ] Implement this `removeBook` action with ES6 arrow function.
```suggestion
const removeBook = (book) => {
```

2021-01-21 19:19 UTC, christianotieno commented on src/components/App.js
> +function App() {
## Implement ES6 syntax
- [ ] Implement this `App` component with ES6 arrow function.
```suggestion
const App = () => {
```

2021-01-21 19:19 UTC, christianotieno commented on src/components/Book.js
> +function Book({ book }) {
## Implement ES6 syntax
- [ ] Implement this `Book` component with ES6 arrow function.
```suggestion
const Book = ({ book }) => {
```

2021-01-21 19:19 UTC, christianotieno commented on src/components/BooksForm.js
> +function BooksForm() {
## Implement ES6 syntax
- [ ] Implement this `BooksForm` component with ES6 arrow function.
```suggestion
const BooksForm = () => {
```

2021-01-21 19:19 UTC, christianotieno commented on src/components/BooksList.js
> +function mapStateToProps(state) {
## Implement ES6 syntax
- [ ] Implement this `mapStateToProps` function's component with ES6 arrow function.
```suggestion
const mapStateToProps = (state) => {
```

2021-01-21 19:19 UTC, christianotieno commented on src/components/BooksList.js
> +function BooksList({ books }) {
## Implement ES6 syntax
- [ ] Implement this `BooksList` component with ES6 arrow function.
```suggestion
const BooksList = ({ books }) => {
```

2021-01-21 19:19 UTC, christianotieno commented on src/reducers/books.js
> +function reducer(state = {}, action) {
## Implement ES6 syntax
- [ ] Implement this `reducer` reducer with ES6 arrow function.
```suggestion
const reducer = (state = {}, action) => {
```
## Implement the `index.js` reducer
- [ ] While at it please ensure you have implemented the `index.js` combine reducer that required to combine your app's reducers. As of now, it is currently empty.

2021-01-22 05:47 UTC, whiz25 approved these changes
## Approved :clap:
Changes made as requested. Syntax follow ES6 syntax. Nice job.
Merge and proceed to the next milestone.


### Martin Afani

2021-01-22 08:51 UTC, merged